# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: rokiexie.github.io
date_format: "ordinal"
title: 谢园rokiexie
subtitle: "欢迎来到谢园的个人主页"
description: "谢园的个人博客"
keywords: 谢园, rokiexie, login, xieyuan
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
source_code: https://github.com/rokeixie
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: xieyuan
organization: Sogou, Inc.
organization_url: https://www.gitbook.com/@rokiexy
location: Shanghai, China
email: rokiexiey@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Socials     #
# ---------------- #
github_username: rokiexie
facebook_username: rokiexie
weibo_username: 海边的蟹
zhihu_username: 谢园谢园
twitter_username: rokiexie

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, duoshuo, changyan
comments_provider: disqus
# !!!重要!!! 请修改下面两个用户名为你自己申请的
# !!!Important!!! Please modify usernames below to yours
duoshuo_username: rokiexie
disqus_username: rokiexie

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1

# ---------------- #
#      Datas       #
# ---------------- #
skill_software_keywords: [Java,  Python]
skill_mobile_app_keywords: [Android]
skill_windows_keywords: [Win32 SDK]
